[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node .output/server/index.mjs"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
