import { NotFoundException } from "@nestjs/common";
import { Test, type TestingModule } from "@nestjs/testing";
import { BacklogsService } from "./backlogs.service";

describe("BacklogsService", () => {
	let service: BacklogsService;

	beforeEach(async () => {
		const module: TestingModule = await Test.createTestingModule({
			providers: [BacklogsService],
		}).compile();

		service = module.get<BacklogsService>(BacklogsService);
	});

	it("should be defined", () => {
		expect(service).toBeDefined();
	});

	it("should create a backlog and add item to it", () => {
		// Create the backlog, capture the generated id
		const createdBacklog = service.createBacklog("Test Backlog");
		const backlogId = createdBacklog.id; // get actual id generated by service

		const item = {
			externalServiceId: 123,
			name: "Test Game",
			coverUrl: "https://example.com/image.jpg",
		};

		const result = service.addItemToBacklog(backlogId, item);

		expect(result).toHaveProperty("id");
		expect(result.name).toBe("Test Game");

		const backlog = service.getBacklog(backlogId);
		expect(backlog).toBeDefined();
		expect(backlog!.items.length).toBe(1);
		expect(backlog!.items[0].externalServiceId).toBe(123);
	});

	it("should return undefined if backlog does not exist", () => {
		const result = service.getBacklog("non-existent");
		expect(result).toBeUndefined();
	});
});
