/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MyGamesRouteImport } from './routes/my-games'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesIdRouteImport } from './routes/games/$id'
import { Route as ApiUserGamesRouteImport } from './routes/api/user-games'
import { Route as ApiUserGamesGameIdRouteImport } from './routes/api/user-games.$gameId'
import { Route as ApiGamesSearchRouteImport } from './routes/api/games/search'
import { Route as ApiGamesPopularRouteImport } from './routes/api/games/popular'
import { Route as ApiGamesIdRouteImport } from './routes/api/games/$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGamesRoute = MyGamesRouteImport.update({
  id: '/my-games',
  path: '/my-games',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIdRoute = GamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserGamesRoute = ApiUserGamesRouteImport.update({
  id: '/api/user-games',
  path: '/api/user-games',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserGamesGameIdRoute = ApiUserGamesGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => ApiUserGamesRoute,
} as any)
const ApiGamesSearchRoute = ApiGamesSearchRouteImport.update({
  id: '/api/games/search',
  path: '/api/games/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesPopularRoute = ApiGamesPopularRouteImport.update({
  id: '/api/games/popular',
  path: '/api/games/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesIdRoute = ApiGamesIdRouteImport.update({
  id: '/api/games/$id',
  path: '/api/games/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/my-games': typeof MyGamesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/user-games': typeof ApiUserGamesRouteWithChildren
  '/games/$id': typeof GamesIdRoute
  '/games/': typeof GamesIndexRoute
  '/api/games/$id': typeof ApiGamesIdRoute
  '/api/games/popular': typeof ApiGamesPopularRoute
  '/api/games/search': typeof ApiGamesSearchRoute
  '/api/user-games/$gameId': typeof ApiUserGamesGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/my-games': typeof MyGamesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/user-games': typeof ApiUserGamesRouteWithChildren
  '/games/$id': typeof GamesIdRoute
  '/games': typeof GamesIndexRoute
  '/api/games/$id': typeof ApiGamesIdRoute
  '/api/games/popular': typeof ApiGamesPopularRoute
  '/api/games/search': typeof ApiGamesSearchRoute
  '/api/user-games/$gameId': typeof ApiUserGamesGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/my-games': typeof MyGamesRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/api/user-games': typeof ApiUserGamesRouteWithChildren
  '/games/$id': typeof GamesIdRoute
  '/games/': typeof GamesIndexRoute
  '/api/games/$id': typeof ApiGamesIdRoute
  '/api/games/popular': typeof ApiGamesPopularRoute
  '/api/games/search': typeof ApiGamesSearchRoute
  '/api/user-games/$gameId': typeof ApiUserGamesGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/my-games'
    | '/sign-in'
    | '/sign-up'
    | '/api/user-games'
    | '/games/$id'
    | '/games/'
    | '/api/games/$id'
    | '/api/games/popular'
    | '/api/games/search'
    | '/api/user-games/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/my-games'
    | '/sign-in'
    | '/sign-up'
    | '/api/user-games'
    | '/games/$id'
    | '/games'
    | '/api/games/$id'
    | '/api/games/popular'
    | '/api/games/search'
    | '/api/user-games/$gameId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/my-games'
    | '/sign-in'
    | '/sign-up'
    | '/api/user-games'
    | '/games/$id'
    | '/games/'
    | '/api/games/$id'
    | '/api/games/popular'
    | '/api/games/search'
    | '/api/user-games/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  MyGamesRoute: typeof MyGamesRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiUserGamesRoute: typeof ApiUserGamesRouteWithChildren
  GamesIdRoute: typeof GamesIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
  ApiGamesIdRoute: typeof ApiGamesIdRoute
  ApiGamesPopularRoute: typeof ApiGamesPopularRoute
  ApiGamesSearchRoute: typeof ApiGamesSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-games': {
      id: '/my-games'
      path: '/my-games'
      fullPath: '/my-games'
      preLoaderRoute: typeof MyGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$id': {
      id: '/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-games': {
      id: '/api/user-games'
      path: '/api/user-games'
      fullPath: '/api/user-games'
      preLoaderRoute: typeof ApiUserGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-games/$gameId': {
      id: '/api/user-games/$gameId'
      path: '/$gameId'
      fullPath: '/api/user-games/$gameId'
      preLoaderRoute: typeof ApiUserGamesGameIdRouteImport
      parentRoute: typeof ApiUserGamesRoute
    }
    '/api/games/search': {
      id: '/api/games/search'
      path: '/api/games/search'
      fullPath: '/api/games/search'
      preLoaderRoute: typeof ApiGamesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/popular': {
      id: '/api/games/popular'
      path: '/api/games/popular'
      fullPath: '/api/games/popular'
      preLoaderRoute: typeof ApiGamesPopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$id': {
      id: '/api/games/$id'
      path: '/api/games/$id'
      fullPath: '/api/games/$id'
      preLoaderRoute: typeof ApiGamesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiUserGamesRouteChildren {
  ApiUserGamesGameIdRoute: typeof ApiUserGamesGameIdRoute
}

const ApiUserGamesRouteChildren: ApiUserGamesRouteChildren = {
  ApiUserGamesGameIdRoute: ApiUserGamesGameIdRoute,
}

const ApiUserGamesRouteWithChildren = ApiUserGamesRoute._addFileChildren(
  ApiUserGamesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  MyGamesRoute: MyGamesRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiUserGamesRoute: ApiUserGamesRouteWithChildren,
  GamesIdRoute: GamesIdRoute,
  GamesIndexRoute: GamesIndexRoute,
  ApiGamesIdRoute: ApiGamesIdRoute,
  ApiGamesPopularRoute: ApiGamesPopularRoute,
  ApiGamesSearchRoute: ApiGamesSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
